queue_rules:
  - name: default
    conditions:
      - label=ready-to-merge
pull_request_rules:
  - name: add to queue
    conditions:
      - label=ready-to-merge
    actions:
      queue:
         name: default
  - name: start ci
    conditions: 
      - base=main
      - queue-position=0
      - label=ready-to-merge
    actions:
      label:
        add:
        - check-ci-end