version: 1.1.0
merge_rules:
  labels:
    trigger: mergequeue
    skip_line: mergequeue-priority
    merge_failed: blocked
    skip_delete_branch: ''
  update_latest: true
  delete_branch: false
  use_rebase: false
  publish_status_check: false
  enable_comments: true
  ci_timeout_mins: 0
  require_all_checks_pass: false
  preconditions:
    validations: []
    number_of_approvals: 0
    required_checks: []
    use_github_mergeability: true
    conversation_resolution_required: false
scenarios: []