name: check-ci-end

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [labeled,synchronize]
jobs:
  check-ci-end:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: check ci-end on latest pr closed
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check last pr
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_LIST=$(gh pr list -B main -s merged -L 1)
          PR_NUMBER=( $PR_LIST[0] )
          GET_LABEL=$(gh pr view $PR_NUMBER)
          if [[ "$GET_LABEL" == *ci-end-fail* ]]; then
            echo 'deploy failed'
            exit 1
          else
            echo 'continuing ...'
          fi
      - name: start CI
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: action-ci-run



