name: sim ci-end

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [labeled]

jobs:
  sim-ci-run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Simulate ci-end
    steps:
      - name: sim jenkins deploy
        shell: bash
        run: sleep 10
      - name: Set Success Status
        run:   |
                CURRENT_SHA=$(git rev-parse HEAD)
                echo "CURRENT_SHA: $CURRENT_SHA"
                curl --location --request POST "https://${{ secrets.ACTION_TOKEN }}@api.github.com/repos/${{ github.repository }}/statuses/$CURRENT_SHA" \
                  --header 'Accept: application/vnd.github.antiope-preview+json' \
                  --header 'Content-Type: application/json' \
                    --data-raw '{
                        "state": "success",
                        "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                        "description": "sucess",
                        "context": "ci-end"
    
