name: sim ci-run

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [labeled]

jobs:
  sim-ci-run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Simulate ci-run
    steps:
      - name: Set Success Status
        run:   |
                CURRENT_SHA=$(git rev-parse HEAD)
                echo "CURRENT_SHA: $CURRENT_SHA"
                curl --location --request POST "https://${{ secrets.ACTION_TOKEN }}@api.github.com/repos/${{ github.repository }}/statuses/$CURRENT_SHA" \
                  --header 'Accept: application/vnd.github.antiope-preview+json' \
                  --header 'Content-Type: application/json' \
                    --data-raw '{
                        "state": "success",
                        "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                        "description": "sucess",
                        "context": "CI Status"
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          number: ${{ steps.setup-workspace.outputs.pr-number }}
          method: squash
      - name: Trigger workflow
        shell: bash
        run: |
          PAYLOAD=""
          URL="https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci-end-sim/dispatches"
          set +e
          curl --fail --silent --show-error -i -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -X POST -d "${PAYLOAD}" "${URL}"
          fi
