name: sim ci-run

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [labeled]

jobs:
  sim-ci-run:
    if: contains(github.event.pull_request.labels.*.name, 'action-ci-run')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Simulate ci-run
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          method: squash
      - name: Trigger workflow
        shell: bash
        run: |
          set +e
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          gh workflow run ci-end-sim.yaml --ref main -f pr_number=${{ github.event.pull_request.number }}
          fi
