name: sim ci-run

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [labeled]

jobs:
  sim-ci-run:
    if: contains(github.event.pull_request.labels.*.name, 'action-ci-run')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Simulate ci-run
    steps:
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          method: squash
      - name: Trigger workflow
        shell: bash
        run: |
          PAYLOAD=""
          URL="https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci-end-sim/dispatches"
          set +e
          curl --fail --silent --show-error -i -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -X POST -d "${PAYLOAD}" "${URL}"
          fi
